"""Build the .xlsm from edited vba/*.bas (.cls) files.

Reads vba/_meta.json for module names, textoffsets, and target compressed sizes.
For each module:
- Reads the source text from vba/<name>.<ext>
- Appends an AUTO_PADDING block of random comments so compressed output exactly
  matches target_compressed_size (required because olefile.write_stream() needs
  identical size).
- Compresses and writes the new compressed source back into vbaProject.bin.

Then:
- Zeros each modified module's PerformanceCache (the bytes before textoffset),
  the version field of _VBA_PROJECT, and the __SRP_* streams. This forces
  Excel to recompile from source rather than trust stale compiled p-code.
- Repackages the .xlsm zip in place.

Usage:
    python scripts/build_vba.py
"""
import hashlib
import io
import json
import os
import shutil
import sys
import zipfile
from pathlib import Path

import olefile
from oletools.olevba import decompress_stream

sys.path.insert(0, str(Path(__file__).resolve().parent))
from ms_ovba_compress import compress_stream

PADDING_START = "' === AUTO_PADDING_START - do not edit, regenerated by build_vba.py ==="
PADDING_END = "' === AUTO_PADDING_END ==="


def make_pad_bytes(n, salt=0):
    """Pseudo-random printable ASCII so MS-OVBA can't compress the pad."""
    out = bytearray()
    counter = salt
    while len(out) < n:
        h = hashlib.sha256(counter.to_bytes(8, 'little')).digest()
        for b in h:
            ascii_b = 0x21 + (b % (0x7E - 0x21 + 1))
            if ascii_b in (0x22, 0x27):  # avoid quotes
                ascii_b = 0x21
            out.append(ascii_b)
            if len(out) >= n:
                break
        counter += 1
    return bytes(out)


def make_padded(base_src_bytes, pad_chars, salt=0):
    """Append a block of random comment lines (auto-padding) totaling ``pad_chars`` chars.

    We don't use sentinels because the sentinel overhead is too large to hit small
    target sizes. extract_vba.py detects these heuristically (trailing comment
    block of random-looking printable ASCII, no spaces).
    """
    if pad_chars <= 0:
        return base_src_bytes
    block = bytearray()
    rand = make_pad_bytes(pad_chars, salt)
    pos = 0
    while pos < len(rand):
        block.extend(b"\r\n' ")
        block.extend(rand[pos:pos + 80])
        pos += 80
    block.extend(b"\r\n")
    return base_src_bytes + bytes(block)


EMPTY_CHUNK = b'\x00\xB0\x00'  # 3-byte MS-OVBA chunk that decompresses to 0 bytes


def make_chunk_padding(n_bytes):
    """Generate ``n_bytes`` of valid MS-OVBA chunks appended after a compressed
    stream. Returns (padding_bytes, extra_decompressed_bytes).

    n_bytes must be 0 or >= 3.
    """
    if n_bytes == 0:
        return b'', 0
    if n_bytes < 3:
        raise ValueError("Chunk-based padding requires gap >= 3 bytes")
    r = n_bytes % 3
    if r == 0:
        return EMPTY_CHUNK * (n_bytes // 3), 0
    if r == 1:
        # (n-4) empties of 3 bytes + one 4-byte chunk (1 literal)
        return EMPTY_CHUNK * ((n_bytes - 4) // 3) + b'\x01\xB0\x00 ', 1
    # r == 2
    return EMPTY_CHUNK * ((n_bytes - 5) // 3) + b'\x02\xB0\x00  ', 2


def pad_to_exact(src_bytes, target, name=""):
    """Pad source + compressed output to exactly ``target`` compressed bytes.

    Strategy:
    1. Pad source with random comment lines to get compressed size just under target
    2. Use MS-OVBA empty/small chunks to fill the remaining 0 or 3+ bytes exactly

    Returns (padded_source_bytes, padded_compressed_bytes).
    """
    base_compressed = compress_stream(src_bytes)
    if len(base_compressed) > target:
        raise RuntimeError(
            f"{name}: source too large; compressed={len(base_compressed)} > target={target}"
        )

    # Find largest pad_chars that produces compressed <= target with gap 0 or >= 3
    best = None  # (pad_chars, salt, padded_src, compressed_bytes, gap)
    for salt in range(0, 20):
        # Coarse upper bound
        hi = 100
        while len(compress_stream(make_padded(src_bytes, hi, salt))) < target:
            hi *= 2
            if hi > 500000:
                break
        # Binary search for smallest pad_chars with compressed >= target
        lo = 0
        while lo < hi:
            mid = (lo + hi) // 2
            if len(compress_stream(make_padded(src_bytes, mid, salt))) >= target:
                hi = mid
            else:
                lo = mid + 1
        # Sweep around lo to find a (pad_chars, gap) that's either 0 or >= 3
        for delta in range(-50, 50):
            pc = lo + delta
            if pc < 0:
                continue
            padded = make_padded(src_bytes, pc, salt)
            c = compress_stream(padded)
            gap = target - len(c)
            if gap < 0:
                continue
            if gap == 0 or gap >= 3:
                if best is None or gap < best[4]:
                    best = (pc, salt, padded, c, gap)
                if gap == 0:
                    return padded, c

    if best is None:
        raise RuntimeError(f"{name}: no valid padding found, base={len(base_compressed)} target={target}")

    pc, salt, padded_src, compressed, gap = best
    padding_bytes, extra_decompressed = make_chunk_padding(gap)
    # The MS-OVBA empty chunks may add a few extra decompressed bytes (spaces) which
    # extract_vba.py strips via the trailing-whitespace cleanup.
    return padded_src, compressed + padding_bytes


def invalidate_caches(ole, meta_modules):
    """Zero PerformanceCache portions + _VBA_PROJECT version + __SRP_* streams.

    Forces Excel to recompile VBA from source on next open.
    """
    for m in meta_modules:
        name = m["name"]
        offset = m["textoffset"]
        cur = ole.openstream(f"VBA/{name}").read()
        new = bytes([0] * offset) + cur[offset:]
        ole.write_stream(f"VBA/{name}", new)

    vp_path = "VBA/_VBA_PROJECT"
    vp = ole.openstream(vp_path).read()
    if len(vp) >= 4:
        new_vp = bytearray(vp)
        new_vp[2] = 0
        new_vp[3] = 0
        ole.write_stream(vp_path, bytes(new_vp))

    for i in range(20):
        sn = f"VBA/__SRP_{i}"
        try:
            srp = ole.openstream(sn).read()
            ole.write_stream(sn, bytes([0] * len(srp)))
        except Exception:
            break


def main():
    repo_root = Path(__file__).resolve().parent.parent
    vba_dir = repo_root / "vba"
    meta_path = vba_dir / "_meta.json"
    if not meta_path.exists():
        sys.exit("vba/_meta.json not found. Run extract_vba.py first.")
    with open(meta_path, encoding='utf-8') as f:
        meta = json.load(f)

    xlsm_path = (repo_root / meta["xlsm_path"]).resolve()
    print(f"Building → {xlsm_path}")

    # Unpack the xlsm to a temp directory next to it
    work_dir = repo_root / ".build_tmp"
    if work_dir.exists():
        shutil.rmtree(work_dir)
    work_dir.mkdir()
    with zipfile.ZipFile(xlsm_path) as z:
        z.extractall(work_dir)

    vba_bin_path = work_dir / "xl" / "vbaProject.bin"

    # Open vbaProject.bin in write mode and update each module
    ole = olefile.OleFileIO(str(vba_bin_path), write_mode=True)
    for m in meta["modules"]:
        name = m["name"]
        src_file = repo_root / m["file"]
        if not src_file.exists():
            print(f"  Skipping {name}: {src_file} not found")
            continue
        with open(src_file, 'rb') as f:
            src_text = f.read()
        target = m["target_compressed_size"]

        # Quick check: if it already fits without padding, no need to pad
        compressed = compress_stream(src_text)
        if len(compressed) > target:
            sys.exit(
                f"{name}: compressed source ({len(compressed)} bytes) exceeds "
                f"target {target}. Reduce the size of edits in {src_file} or "
                f"shrink another module to free room."
            )

        final_src, final_compressed = pad_to_exact(src_text, target, name=name)
        assert len(final_compressed) == target

        cur = ole.openstream(f"VBA/{name}").read()
        header = cur[:m["textoffset"]]
        new_stream = header + final_compressed
        assert len(new_stream) == m["stream_size"], (
            f"{name}: stream size mismatch — expected {m['stream_size']}, "
            f"got {len(new_stream)}"
        )
        ole.write_stream(f"VBA/{name}", new_stream)
        print(f"  ✓ {name}: source {len(src_text)} bytes → compressed {target} "
              f"(padded source {len(final_src)})")

    invalidate_caches(ole, meta["modules"])
    ole.close()
    print("  ✓ Cache invalidation done")

    # Repackage the zip
    tmp_xlsm = xlsm_path.with_suffix(".xlsm.tmp")
    if tmp_xlsm.exists():
        tmp_xlsm.unlink()

    all_files = []
    for root, _, files in os.walk(work_dir):
        for f in files:
            full = Path(root) / f
            rel = full.relative_to(work_dir).as_posix()
            all_files.append((full, rel))
    all_files.sort(key=lambda x: (x[1] != "[Content_Types].xml", x[1]))

    with zipfile.ZipFile(tmp_xlsm, 'w', compression=zipfile.ZIP_DEFLATED, compresslevel=6) as z:
        for full, rel in all_files:
            z.write(full, rel)

    shutil.rmtree(work_dir)
    os.replace(tmp_xlsm, xlsm_path)
    print(f"\n✓ Repackaged: {xlsm_path}")


if __name__ == "__main__":
    main()
