"""Extract VBA module sources from the .xlsm into vba/*.bas (.cls) text files.

Usage:
    python scripts/extract_vba.py                # extracts from default xlsm
    python scripts/extract_vba.py path/file.xlsm # extracts from a specific xlsm

For each module in vbaProject.bin (Module1, ThisWorkbook, Sheet1, etc.):
- Decompresses the source code
- Strips any auto-padding block (marked by sentinels) added by build_vba.py
- Writes to vba/<ModuleName>.<ext> as Shift-JIS text (cp932)

A meta file vba/_meta.json is written with textoffsets and target compressed
sizes that build_vba.py needs.
"""
import io
import json
import os
import struct
import sys
import zipfile
from pathlib import Path

import olefile
from oletools.olevba import decompress_stream

PADDING_START = "' === AUTO_PADDING_START - do not edit, regenerated by build_vba.py ==="
PADDING_END = "' === AUTO_PADDING_END ==="

# Module name → file extension
EXT_BY_NAME = {
    "ThisWorkbook": "cls",
    "Sheet1": "cls",
    "Sheet2": "cls",
    "Sheet3": "cls",
    "Sheet4": "cls",
    "Sheet5": "cls",
    "Sheet6": "cls",
    "Module1": "bas",
}


def parse_dir(dir_data):
    """Parse the decompressed dir stream to find module names and textoffsets."""
    modules = []
    cur = None
    i = 0
    while i < len(dir_data) - 6:
        if dir_data[i:i + 2] == b'\x19\x00':
            rec_size = struct.unpack("<I", dir_data[i + 2:i + 6])[0]
            if 0 < rec_size < 100:
                name = dir_data[i + 6:i + 6 + rec_size].decode('cp932', errors='replace')
                cur = {'name': name}
                modules.append(cur)
        elif dir_data[i:i + 2] == b'\x31\x00':
            rec_size = struct.unpack("<I", dir_data[i + 2:i + 6])[0]
            if rec_size == 4 and cur is not None:
                offset = struct.unpack("<I", dir_data[i + 6:i + 10])[0]
                cur['offset'] = offset
        i += 1
    return modules


def strip_padding(text):
    """Remove auto-padding block from source text.

    Handles two cases:
    1. New format with sentinels (PADDING_START / PADDING_END markers)
    2. Legacy format: trailing block of long random-looking comment lines
       (added by earlier versions of build that pre-date the sentinels)
    """
    # Case 1: sentinel-marked padding
    if PADDING_START in text:
        idx = text.find(PADDING_START)
        leading = text.rfind('\r\n', 0, idx)
        if leading < 0:
            leading = 0
        end_idx = text.find(PADDING_END, idx)
        if end_idx < 0:
            return text
        after = text.find('\r\n', end_idx)
        if after < 0:
            return text[:leading]
        return text[:leading] + text[after:]

    # Case 2: legacy long-random-comment-line padding (heuristic)
    lines = text.split('\r\n')

    def looks_random_ascii(body):
        return body != '' and all(0x21 <= ord(ch) <= 0x7E for ch in body) and ' ' not in body

    # Find a "definite" padding line (random-looking ASCII comment) near the end.
    # Threshold: body ≥ 10 chars, no spaces, all printable ASCII, mix of char types.
    def is_definite_pad(body):
        if len(body) < 10 or ' ' in body:
            return False
        if not all(0x21 <= ord(ch) <= 0x7E for ch in body):
            return False
        has_alpha = any(ch.isalpha() for ch in body)
        has_other = any(not ch.isalnum() for ch in body)
        return has_alpha and has_other

    definite_idx = None
    scan_from = max(-1, len(lines) - 300)
    for i in range(len(lines) - 1, scan_from, -1):
        line = lines[i]
        if line.startswith("' ") and is_definite_pad(line[2:]):
            definite_idx = i
            break
    if definite_idx is None:
        return text

    # Expand backwards: include all contiguous comment-or-blank lines whose body
    # is blank or random-ASCII (catches the short tail and any blanks before)
    first_pad = definite_idx
    for i in range(definite_idx - 1, -1, -1):
        line = lines[i]
        if line.strip() == '':
            first_pad = i
            continue
        if line.startswith("'"):
            body = line[1:].lstrip(' ')
            if body == '' or looks_random_ascii(body):
                first_pad = i
                continue
        break

    # Expand forwards: include trailing pad lines (the 'n' tail line, etc.)
    last_pad = definite_idx
    for i in range(definite_idx + 1, len(lines)):
        line = lines[i]
        if line.strip() == '':
            last_pad = i
            continue
        if line.startswith("'"):
            body = line[1:].lstrip(' ')
            if body == '' or looks_random_ascii(body):
                last_pad = i
                continue
        break

    cleaned = lines[:first_pad] + lines[last_pad + 1:]
    return '\r\n'.join(cleaned).rstrip('\r\n') + '\r\n'


def main():
    xlsm_path = sys.argv[1] if len(sys.argv) > 1 else "進度予定表システム_鳴海.xlsm"
    repo_root = Path(__file__).resolve().parent.parent
    xlsm_full = (repo_root / xlsm_path).resolve()
    vba_dir = repo_root / "vba"
    vba_dir.mkdir(exist_ok=True)

    print(f"Reading {xlsm_full}")
    with zipfile.ZipFile(xlsm_full) as z:
        vba_bin = z.read("xl/vbaProject.bin")

    ole = olefile.OleFileIO(io.BytesIO(vba_bin))
    dir_raw = ole.openstream("VBA/dir").read()
    dir_data = decompress_stream(bytearray(dir_raw))
    modules = parse_dir(dir_data)

    meta = {"xlsm_path": xlsm_path, "modules": []}
    for m in modules:
        name = m["name"]
        textoffset = m.get("offset")
        if textoffset is None:
            print(f"  Skipping {name}: no textoffset found")
            continue
        stream = ole.openstream(f"VBA/{name}").read()
        compressed = stream[textoffset:]
        target_compressed_size = len(compressed)
        src_bytes = decompress_stream(bytearray(compressed))
        src_text = src_bytes.decode('cp932', errors='replace')
        clean_text = strip_padding(src_text)
        # Also strip any trailing whitespace/junk left by chunk-based padding
        # (the 4/5-byte MS-OVBA padding chunks add 1-2 space chars at the end).
        clean_text = clean_text.rstrip() + '\r\n'

        ext = EXT_BY_NAME.get(name, "bas")
        out_path = vba_dir / f"{name}.{ext}"
        with open(out_path, 'w', encoding='cp932', newline='') as f:
            f.write(clean_text)
        meta["modules"].append({
            "name": name,
            "file": f"vba/{name}.{ext}",
            "textoffset": textoffset,
            "target_compressed_size": target_compressed_size,
            "stream_size": len(stream),
        })
        print(f"  ✓ {name}: {len(src_bytes)} bytes source → vba/{name}.{ext} "
              f"(stripped {len(src_text) - len(clean_text)} pad bytes)")

    ole.close()

    meta_path = vba_dir / "_meta.json"
    with open(meta_path, 'w', encoding='utf-8') as f:
        json.dump(meta, f, ensure_ascii=False, indent=2)
    print(f"\n✓ Wrote meta: {meta_path}")


if __name__ == "__main__":
    main()
